name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        php: [ '8.3', '8.4' ]

    runs-on: 'ubuntu-latest'

    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php}}

    - name: Install
      run: |
        composer install

    - name: Test
      run: |
        composer test
